tools:
  - name: grant
    version:
      want: current
    method: go-install
    with:
      module: .
      entrypoint: cmd/grant

  - name: binny
    version:
      # can be 'main', 'latest', or a specific version
      want: v0.3.0
    method: github-release
    with:
      repo: anchore/binny

  - name: task
    version:
      want: v3.30.1
    method: github-release
    with:
      repo: go-task/task

  - name: gosimports
    version:
      want: v0.3.8
    method: github-release
    with:
      repo: rinchsan/gosimports

  - name: golangci-lint
    version:
      want: v1.54.2
    method: github-release
    with:
      repo: golangci/golangci-lint

  - name: chronicle
    version:
      want: v0.8.0
    method: github-release
    with:
      repo: anchore/chronicle

  - name: glow
    version:
      want: v1.5.1
    method: github-release
    with:
      repo: charmbracelet/glow

  - name: goreleaser
    version:
      want: v1.21.1
    method: github-release
    with:
      repo: goreleaser/goreleaser
