tools:
  - name: grant
    version:
      want: current
    method: go-install
    with:
      module: .
      entrypoint: cmd/grant
      ldflags:
        - -X main.version={{ .Version }}
        - -X main.gitCommit={{ .Version }}
        - -X main.gitDescription={{ .Version }}
        # note: sprig functions are available: http://masterminds.github.io/sprig/
        - -X main.buildDate={{ now | date "2006-01-02T15:04:05Z07:00" }}

  - name: binny
    version:
      want: v0.6.2
    method: github-release
    with:
      repo: anchore/binny

  - name: gh
    version:
      want: v2.35.0
    method: github-release
    with:
      repo: cli/cli

  - name: quill
    version:
      want: v0.4.1
    method: github-release
    with:
      repo: anchore/quill

  - name: chronicle
    version:
      want: v0.8.0
    method: github-release
    with:
      repo: anchore/chronicle

  - name: gosimports
    version:
      want: v0.3.8
    method: github-release
    with:
      repo: rinchsan/gosimports

  - name: glow
    version:
      want: v1.5.1
    method: github-release
    with:
      repo: charmbracelet/glow

  # used for signing the checksums file at release
  - name: cosign
    version:
      want: v3.0.2
    method: github-release
    with:
      repo: sigstore/cosign

  - name: goreleaser
    version:
      want: v2.3.2
    method: github-release
    with:
      repo: goreleaser/goreleaser

  - name: golangci-lint
    version:
      want: v2.4.0
    method: github-release
    with:
      repo: golangci/golangci-lint

  - name: bouncer
    version:
      want: v0.4.0
    method: github-release
    with:
      repo: wagoodman/go-bouncer

  - name: task
    version:
      want: v3.30.1
    method: github-release
    with:
      repo: go-task/task

  - name: syft
    version:
      want: v1.2.0
    method: github-release
    with:
      repo: anchore/syft

  - name: vhs
    version:
      want: v0.10.0
    method: github-release
    with:
      repo: charmbracelet/vhs
