# only pull in version updates that were released more than a week ago (low-pass filter for quickly-retracted releases)
cooldown: 7d
# note: we are inheriting tool definitions from anchore/go-make .binny.yaml, so we only need to specify tools here that
# are not already defined there (or that we want to override with different versions)
tools:
  # used to dogfood grant's license check against its own dependencies
  - name: grant
    version:
      want: current
    method: go-install
    with:
      module: .
      entrypoint: cmd/grant
      ldflags:
        - -X main.version={{ .Version }}
        - -X main.gitCommit={{ .Version }}
        - -X main.gitDescription={{ .Version }}
        # note: sprig functions are available: http://masterminds.github.io/sprig/
        - -X main.buildDate={{ now | date "2006-01-02T15:04:05Z07:00" }}

  # used to render the changelog when running `make changelog` locally
  - name: glow
    version:
      want: v2.1.2
    method: github-release
    with:
      repo: charmbracelet/glow

  # used to generate the project demo GIF
  - name: vhs
    version:
      want: v0.11.0
    method: github-release
    with:
      repo: charmbracelet/vhs
