# golangci-lint v2.4.0
issues:
  max-same-issues: 25
  uniq-by-line: false
  # Don't report findings from dependencies
  exclude-dirs:
    - "*/go/pkg/mod/*"

linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    # NOTE: If you use gosimports/gci elsewhere, keep goimports disabled to avoid conflicts.
    # - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  funlen:
    lines: 70        # default 60
    statements: 50   # default 40

  # Make sure typechecking uses the correct language level.
  # (golangci-lint v2.* can pass this through to tools that support it.)
  typecheck:
    go: "1.25"

  staticcheck:
    # Keep staticcheck aligned with your Go version so rules don’t over/under-report.
    go: "1.25"
    checks: ["all"]  # you can list exclusions here later if needed

  revive:
    # A sane base; add/override rules as your project needs evolve.
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-naming
      - name: errorf
      - name: exported
      - name: imports-blacklist
        disabled: true     # enable with a curated list if you want depguard-like behavior
      - name: if-return
      - name: receiver-naming
      - name: indent-error-flow
      - name: var-naming
      - name: time-naming
      - name: unexported-naming
      - name: package-comments
        disabled: true     # TODO: enable when you add top-level package doc coverage

run:
  timeout: 10m
  # Make linting deterministic and ensure deps are fetched when needed.
  modules-download-mode: mod
  # If you build with tags, set them here so typecheck matches your build:
  # build-tags:
  #   - netgo
  #   - osusergo

output:
  sort-results: true
  print-issued-lines: true
  # Keep output stable across environments (paths can vary in CI/local).
  path-prefix: ""

# Keep as reference for things you explicitly do NOT want enabled:
# - deadcode (replaced by 'unused')
# - structcheck, varcheck (replaced by 'unused')
# - golint (deprecated)
# - scopelint (deprecated)
# - rowserrcheck (not useful here / generics issues)
# - gochecknoglobals/gochecknoinits (too aggressive)
# - lll (no per-line exceptions)
# - prealloc (not consistently beneficial)
# - wsl (no autofixer; noisy)
