# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

release:
  prerelease: auto
  draft: false

env:
  # required to support multi architecture docker builds
  - CGO_ENABLED=0

builds:
  - id: linux-build
    dir: ./cmd/grant
    binary: grant
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    # set the modified timestamp on the output binary to the git timestamp to ensure a reproducible build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags '-static'
      -X main.version={{.Version}}
      -X main.gitCommit={{.Commit}}
      -X main.buildDate={{.Date}}
      -X main.gitDescription={{.Summary}}

  - id: darwin-build
    dir: ./cmd/grant
    binary: grant
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: *build-timestamp
    ldflags: *build-ldflags
    hooks:
      post:
        - cmd: .tool/quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} -vv
          env:
            - QUILL_LOG_FILE=/tmp/quill-{{ .Target }}.log

archives:
  - id: linux-archives
    builds:
      - linux-build
  - id: darwin-archives
    builds:
      - darwin-build

nfpms:
  - license: "Apache 2.0"
    maintainer: "Anchore, Inc"
    homepage: &website "https://github.com/anchore/grant"
    description: &description "A tool consumes SBOMS and details license information"
    formats:
      - rpm
      - deb

brews:
  - repository:
      owner: anchore
      name: homebrew-grant
      token: "{{.Env.GITHUB_BREW_TOKEN}}"
    ids:
      - darwin-archives
      - linux-archives
    homepage: *website
    description: *description
    license: "Apache License 2.0"

sboms:
  - artifacts: archive
    # this is relative to the snapshot/dist directory, not the root of the repo
    cmd: ../.tool/syft
    documents:
      - "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom"
    args:
      - "scan"
      - "$artifact"
      - "--output"
      - "json=$document"

signs:
  - cmd: .tool/cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--use-signing-config=false"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

dockers:
  - image_templates:
      - anchore/grant:{{.Tag}}-amd64
      - ghcr.io/anchore/grant:{{.Tag}}-amd64
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--provenance=false"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - anchore/grant:{{.Tag}}-arm64v8
      - ghcr.io/anchore/grant:{{.Tag}}-arm64v8
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--provenance=false"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - anchore/grant:{{.Tag}}-ppc64le
      - ghcr.io/anchore/grant:{{.Tag}}-ppc64le
    goarch: ppc64le
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/ppc64le"
      - "--provenance=false"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - anchore/grant:{{.Tag}}-s390x
      - ghcr.io/anchore/grant:{{.Tag}}-s390x
    goarch: s390x
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/s390x"
      - "--provenance=false"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - anchore/grant:{{.Tag}}-debug-amd64
      - ghcr.io/anchore/grant:{{.Tag}}-debug-amd64
    goarch: amd64
    dockerfile: Dockerfile.debug
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--provenance=false"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - anchore/grant:{{.Tag}}-debug-arm64v8
      - ghcr.io/anchore/grant:{{.Tag}}-debug-arm64v8
    goarch: arm64
    dockerfile: Dockerfile.debug
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--provenance=false"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - anchore/grant:{{.Tag}}-debug-ppc64le
      - ghcr.io/anchore/grant:{{.Tag}}-debug-ppc64le
    goarch: ppc64le
    dockerfile: Dockerfile.debug
    use: buildx
    build_flag_templates:
      - "--platform=linux/ppc64le"
      - "--provenance=false"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      - anchore/grant:{{.Tag}}-debug-s390x
      - ghcr.io/anchore/grant:{{.Tag}}-debug-s390x
    goarch: s390x
    dockerfile: Dockerfile.debug
    use: buildx
    build_flag_templates:
      - "--platform=linux/s390x"
      - "--provenance=false"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

docker_manifests:
  - name_template: anchore/grant:latest
    image_templates:
      - anchore/grant:{{.Tag}}-amd64
      - anchore/grant:{{.Tag}}-arm64v8
      - anchore/grant:{{.Tag}}-ppc64le
      - anchore/grant:{{.Tag}}-s390x

  - name_template: ghcr.io/anchore/grant:latest
    image_templates:
      - ghcr.io/anchore/grant:{{.Tag}}-amd64
      - ghcr.io/anchore/grant:{{.Tag}}-arm64v8
      - ghcr.io/anchore/grant:{{.Tag}}-ppc64le
      - ghcr.io/anchore/grant:{{.Tag}}-s390x

  - name_template: anchore/grant:{{.Tag}}
    image_templates:
      - anchore/grant:{{.Tag}}-amd64
      - anchore/grant:{{.Tag}}-arm64v8
      - anchore/grant:{{.Tag}}-ppc64le
      - anchore/grant:{{.Tag}}-s390x

  - name_template: ghcr.io/anchore/grant:{{.Tag}}
    image_templates:
      - ghcr.io/anchore/grant:{{.Tag}}-amd64
      - ghcr.io/anchore/grant:{{.Tag}}-arm64v8
      - ghcr.io/anchore/grant:{{.Tag}}-ppc64le
      - ghcr.io/anchore/grant:{{.Tag}}-s390x

  - name_template: anchore/grant:debug
    image_templates:
      - anchore/grant:{{.Tag}}-debug-amd64
      - anchore/grant:{{.Tag}}-debug-arm64v8
      - anchore/grant:{{.Tag}}-debug-ppc64le
      - anchore/grant:{{.Tag}}-debug-s390x

  - name_template: ghcr.io/anchore/grant:debug
    image_templates:
      - ghcr.io/anchore/grant:{{.Tag}}-debug-amd64
      - ghcr.io/anchore/grant:{{.Tag}}-debug-arm64v8
      - ghcr.io/anchore/grant:{{.Tag}}-debug-ppc64le
      - ghcr.io/anchore/grant:{{.Tag}}-debug-s390x

  - name_template: anchore/grant:{{.Tag}}-debug
    image_templates:
      - anchore/grant:{{.Tag}}-debug-amd64
      - anchore/grant:{{.Tag}}-debug-arm64v8
      - anchore/grant:{{.Tag}}-debug-ppc64le
      - anchore/grant:{{.Tag}}-debug-s390x

  - name_template: ghcr.io/anchore/grant:{{.Tag}}-debug
    image_templates:
      - ghcr.io/anchore/grant:{{.Tag}}-debug-amd64
      - ghcr.io/anchore/grant:{{.Tag}}-debug-arm64v8
      - ghcr.io/anchore/grant:{{.Tag}}-debug-ppc64le
      - ghcr.io/anchore/grant:{{.Tag}}-debug-s390x
