#.grant.yaml
show-packages: true
rules: 
  - pattern: "*gpl*"
    mode: "deny"
    reason: "GPL licenses are not allowed"
    exceptions:
      - "lib*"
  - pattern: "*gfdl*"
    mode: "deny"
    reason: "GPL licenses are not allowed"
