name: "Validations"
on:
  merge_group:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  Static-Analysis:
    # Note: changing this job name requires making the same update in the .github/workflows/release.yaml pipeline
    name: "Static analysis"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - name: Bootstrap environment
        uses: anchore/go-make/.github/actions/setup@88c36505984649108439f13fb35dcaea4ce61d94 # v0.4.0

      - name: Run static analysis
        run: make static-analysis

  Unit-Test:
    # Note: changing this job name requires making the same update in the .github/workflows/release.yaml pipeline
    name: "Unit tests"
    needs: All-Unit-Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: echo All Unit Tests passed

  All-Unit-Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-14
    permissions:
      contents: read
    steps:
      - name: Bootstrap environment
        uses: anchore/go-make/.github/actions/setup@88c36505984649108439f13fb35dcaea4ce61d94 # v0.4.0

      - name: Run unit tests
        run: make unit

  Build-Snapshot-Artifacts:
    # Note: changing this job name requires making the same update in the .github/workflows/release.yaml pipeline
    name: "Build snapshot artifacts"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Bootstrap environment
        uses: anchore/go-make/.github/actions/setup@88c36505984649108439f13fb35dcaea4ce61d94 # v0.4.0
        with:
          # why have another build cache key? We don't want unit/integration/etc test build caches to replace
          # the snapshot build cache, which includes builds for all OSs and architectures. As long as this key is
          # unique from the build-cache-key-prefix in other CI jobs, we should be fine.
          #
          # note: ideally this value should match what is used in release (just to help with build times).
          cache-key-prefix: "snapshot"

      - name: Build snapshot artifacts
        run: make snapshot
